### ISSUE TITLE
Releasing model weights

### ISSUE THREAD

**Issue by hippotabek** [ZhangXInFD/soundstorm-speechtokenizer#2]
Are you planning to release trained model weights?

**Comment by ZhangXInFD** [comment]
We will release the model weights trained on LibriSpeech next week.

**Comment by ZhangXInFD** [comment]
Model weights trained on LibriSpeech have been released in [soundstorm](https://huggingface.co/fnlp/USLM/tree/main/SoundStorm_LibriSpeech).
