### ISSUE TITLE
training code of speechtokenizer

### ISSUE THREAD

**Issue by YuuhangJia** [ZhangXInFD/soundstorm-speechtokenizer#7]
Excuse me, are you planning to release the training code section related to speechtokenizer? This may make our reproduction of the entire work more complete and convincing.

**Comment by ZhangXInFD** [comment]
We have released SpeechTokenizer training code and configuration. Please checkout it on https://github.com/ZhangXInFD/SpeechTokenizer

**Comment by YuuhangJia** [comment]
Thanks a lot!
